version: '3.5'

services:
  bot:
    build: .
    image: unibot:${BOT_VERSION}
    env_file:
      - ../unibo_orari_bot-env/bot.env
    environment:
      BOT_VERSION: ${BOT_VERSION}
    volumes:
        - bot-data:/app-data
    restart: unless-stopped

volumes:
    bot-data:
